# Generated by Django 4.1.4 on 2024-07-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='area_apartment',
            field=models.IntegerField(default=0, help_text='Area of Apartment', verbose_name='Area'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='wifi_availability',
            field=models.BooleanField(default=True, help_text='Check False is Wifi Not Avaibility', verbose_name='Wifi Availability'),
        ),
    ]
