# Generated by Django 4.1.4 on 2024-07-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_remove_apartment_images_apartment_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimage',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Description About Image'),
        ),
    ]
