# Generated by Django 4.1.4 on 2024-08-22 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='cancellation_hours',
            field=models.IntegerField(default=24, verbose_name='Cancellation Days'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_svg', models.TextField(blank=True, null=True)),
                ('icon_font_awesome', models.CharField(blank=True, max_length=100, null=True)),
                ('is_main', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartments.category')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='options',
            field=models.ManyToManyField(related_name='apartments', to='apartments.option'),
        ),
    ]
