# Generated by Django 4.1.4 on 2024-08-23 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_category_apartment_cancellation_hours_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='features',
        ),
    ]
