# Generated by Django 4.1.4 on 2024-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_remove_apartment_cancellation_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=6, verbose_name='Cleaning Fee'),
        ),
    ]
