# Generated by Django 4.1.4 on 2024-08-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_apartment_cleaning_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage for the passenger (e.g., 10.50 for 10.5%)', max_digits=5),
        ),
    ]
