# Generated by Django 4.1.4 on 2024-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_apartment_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='promotional_text',
            field=models.CharField(blank=True, help_text='Writing a promotional text about the apartment', max_length=30, null=True, verbose_name='Promotional Text'),
        ),
    ]
