# Generated by Django 4.1.4 on 2024-09-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_remove_apartment_location_apartment_location_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='location_url',
            field=models.URLField(blank=True, help_text='Location of the apartment', max_length=300, null=True, verbose_name='Location'),
        ),
    ]
