# Generated by Django 4.1.4 on 2024-10-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0014_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
