# Generated by Django 4.1.4 on 2024-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_faq_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Phone')),
                ('legal_phone', models.CharField(max_length=20, verbose_name='Legal Phone')),
                ('legal_email', models.EmailField(max_length=254, verbose_name='Legal Email')),
                ('vat_id', models.CharField(max_length=20, verbose_name='Vat ID')),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payments')], max_length=20),
        ),
    ]
