# Generated by Django 4.1.4 on 2024-10-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_sitecontent_alter_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
