# Generated by Django 4.1.4 on 2024-10-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_sitecontent_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='location',
            field=models.CharField(default='', max_length=100, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
