# Generated by Django 4.1.4 on 2024-10-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0019_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('pending_request', 'Pending Request'), ('booking_modification', 'Booking Modification'), ('deposit_payment', 'Deposit Payment'), ('upcoming_date', 'Upcoming Date'), ('service_review', 'Service Review'), ('complete_information', 'Complete Information')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
