# Generated by Django 4.1.4 on 2024-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0020_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('cancel_confirmation', 'Booking Cancel'), ('pending_request', 'Pending Request'), ('booking_modification', 'Booking Modification'), ('deposit_payment', 'Deposit Payment'), ('upcoming_date', 'Upcoming Date'), ('service_review', 'Service Review'), ('complete_information', 'Complete Information')], max_length=50),
        ),
    ]
