# Generated by Django 4.1.4 on 2024-07-06 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the reservation', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='End date of the reservation.', verbose_name='End Date')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total Price for the reservations.', max_digits=10, verbose_name='Total Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the reservation was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and Time when the reservation was updated.', verbose_name='Updated At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the reservation.', max_length=20, verbose_name='Status')),
                ('apartment', models.ForeignKey(help_text='Apartment being reserved.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='apartments.apartment', verbose_name='Apartment')),
                ('user', models.ForeignKey(help_text='User who made the reservation.', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Terant Name')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
