# Generated by Django 4.1.4 on 2024-08-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_num_guest_alter_reservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='num_night',
            field=models.IntegerField(default=0, help_text='Number of Nights', verbose_name='Number Of Night'),
            preserve_default=False,
        ),
    ]
