# Generated by Django 4.1.4 on 2024-08-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_num_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_options',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('full_payment', 'Full Payment')], default='deposit', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('declined', 'Declined ')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total Price for the reservations.', max_digits=10, null=True, verbose_name='Total Price'),
        ),
    ]
