# Generated by Django 4.1.4 on 2024-08-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_payment_payment_options_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={},
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount', max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount', max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='services_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Services Fee'),
            preserve_default=False,
        ),
    ]
