# Generated by Django 4.1.4 on 2024-09-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_alter_reservation_options_payment_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Services Fee'),
            preserve_default=False,
        ),
    ]
