# Generated by Django 4.1.4 on 2024-09-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_alter_reservation_options_reservation_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sub Total'),
        ),
    ]
