# Generated by Django 4.1.4 on 2024-09-14 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0013_alter_apartment_location_url'),
        ('reservation', '0009_alter_reservation_sub_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartments.apartment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
