# Generated by Django 4.1.4 on 2024-10-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_review_apartment_alter_review_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_method',
            field=models.CharField(choices=[('by_user', 'By User'), ('by_airbnb', 'From Airbnb'), ('by_booking', 'From Booking')], default='by_user', max_length=30),
        ),
    ]
